[package]
name = "signals"
version = "0.2.1"
edition = "2024"
repository = "https://github.com/jensyt/timesignal"

[dependencies]
time = { path = "../time" }

[dev-dependencies]
time = { path = "../time", features = ["std", "now"] }

[features]
std = ["time/std"]
